### PR TITLE
Add more space around instructions.

### PR DESCRIPTION
**Pull request by rocky-jaiswal**
Fix for #474

### CODE REVIEW

**Comment by rocky-jaiswal** [comment]
This solves the problem on small screens - 

new_clojars

However on large screens, the instructions appear on a single line (not sure if this would be a problem or not) - 

new_clojars2

**Comment by danielcompton** [comment]
Hi @rocky-jaiswal thanks for this. I suspect there may be a simpler way to solve this. Removing the `.hero-text` class from the `h2` makes it fit the width correctly like a Bootstrap `row` should automatically, but doesn't set the font height correctly. 

After doing some more investigation, just setting the text containers to `col-sm-12` seems to alleviate the problem. But it introduces awkward text wrapping over the two divs though. 

There are two places where this is a problem: `body > div.hero.row > header > h2` and `body > div.hero.row > h2`.

I don't quite understand how/why Bootstrap is combining two div's with `col-md-12` on smaller device screens, but I think if we can work that out, we should be able to fix this quite cleanly.

**Comment by rocky-jaiswal** [comment]
Thanks for your feedback. I will investigate more and come up with something.

**Comment by rocky-jaiswal** [comment]
For md-12 the display is inlined because of this line - 

https://github.com/clojars/clojars-web/blob/master/resources/public/stylesheets/screen.css#L513

It also is inside a media query (line 465) so it only kicks in for small screen. 

Let me know what you think the best solution would be, I will be happy to help implement it :)

**Comment by spencercrissman** [comment]
I think all that is required is to remove the 'row' class from the h2 that is currently wrapped around the instructions? I think it is confusing the layout of the elements inside it.

**Comment by tobias** [comment]
Closing as this was superseded by https://github.com/clojars/clojars-web/pull/581

**Pull request closed without merging**
