### PR TITLE
WIP: Refactoring to use consistent names for :group-id/:artifact-id

### PR DESCRIPTION
**Pull request by firthh**
Addressing issue #525 
It's still work in progress but I thought I'd open an issue so that there would be more visibility into some of the changes as there are going to be a lot of them.

### CODE REVIEW

**Comment by tobias** [comment]
Thanks for tackling this. You are a saint for taking it on. I made some changes to the jar page (https://github.com/clojars/clojars-web/commit/279c58373aaacce10c15d1279e45227c3001a785) that may impact your work, sorry if that makes for painful merging.

**Comment by firthh** [comment]
@tobias Thankfully I've been focusing on `:group-id` so far so there were no conflicts rebasing.

Considering how many changes there are already so far I think it would be nice break this down into smaller chunks so it can get merged in sooner. I'm open to suggestions as to what might be a nice way to break this down?

**Comment by tobias** [comment]
@firthh apologies for letting this linger for so long. Is this something you would like to pick back up? If so, I'm happy to help with it.

**Comment by tobias** [comment]
This was closed when I renamed the `master` branch to `main`. Feel free to restart the discussion here if you want to continue working on this.

**Pull request closed without merging**
