### PR TITLE
Allow removing users from groups, add admin users

### PR DESCRIPTION
**Pull request by mynomoto**
Fixes https://github.com/clojars/clojars-web/issues/151

This is not finished but is ready for a first round of reviews. It needs more polishing on the ui and is missing integration tests. I think that one more migration will be necessary to `add added_by "clojars"` for members that have it set to null.

Let me know what you think.

### CODE REVIEW

**Comment by kahunamoore** [comment]
mynomoto: Nice work on this feature!

**Comment by tobias** [comment]
Thanks for this! This looks like a good start. I played with this locally using a copy of the prod db, and have a few comments:

* I agree, we should have a migration for groups with a `null` `added_by` - there are quite a few of those
* I think I'd prefer to have one form for adding a member instead of two, and have a field for the username and a checkbox for the admin option
* When I go to a group that I created but has other members, we're all listed as "Member", and I only have the option to make one of the *other* members an admin, not myself. As soon as I do make another member an admin, I lose the ability to modify the memberships, so can't be admin myself

Other than that, I think this looks good.

**Comment by mynomoto** [comment]
@tobias
* I added the `added_by` migration from `null` to `"clojars"`
* Made a single form for adding new members
* Fixed the issue where when there were no admins in a group one member could make another one an admin.
* Improved the table style.

Can you take another look?

**Comment by tobias** [comment]
I've made some additional commits, so moving to #633

**Pull request closed without merging**
