### PR TITLE
Pushing jars with Boot

### LINKED ISSUE #578: Add Boot instructions to index page
As a followup to #575, it would also be good to include deploy instructions for Boot users to the index page if that is straightforward.

### PR DESCRIPTION
**Pull request by sgerrand**
💁  This change adds a section on how to push jars to Clojars with Boot to the web index page.

Closes #578

### CODE REVIEW

**Comment by sgerrand** [comment]
👋  @tobias: Would you please review these changes.

**Comment by danielcompton** [comment]
@sgerrand can you fix the tests? It looks like there's a syntax problem with mismatched `]`.

**Comment by sgerrand** [comment]
> can you fix the tests?

😊  Apologies, sorting that out now.

**Comment by sgerrand** [comment]
@danielcompton: Should be 👌  now.

**Comment by tobias** [comment]
Thanks for looking at this. However. there are a few issues with the layout:

screen shot 2016-10-08 at 8 14 28 pm

I think I'd rather see boot as a third column in the middle between lein and maven, and not mention bootlaces in the block, but in the header. Maybe with "Push with Boot (using _bootlaces_)".

**Comment by sgerrand** [comment]
> I think I'd rather see boot as a third column in the middle between lein and maven, and not mention bootlaces in the block, but in the header. Maybe with "Push with Boot (using _bootlaces_)".

👌  I'll work on implementing those changes now.

**Comment by sgerrand** [comment]
@tobias: I've revamped the layout, as you requested:

three column layout

Let me know what you think.

**Comment by tobias** [comment]
Thanks!

**Pull request merged**
